batteryChargingSpaceDetected = "Battery Charging Space Detected"	-- (position)
computerRegistered = "Computer Registered"							-- (id)
emptyBatteryDetected = "Empty Battery Detected"						-- (position)
turtleRegistered = "Turtle Registered"								-- (id)
taskFinished = "Task Finished"										-- (id)
