batteryFarmer =					"computers/batteryFarmer.lua"
batteryMonitor =				"computers/batteryMonitor.lua"
turtle =						"computers/turtle.lua"
parkingManager =				"computers/parkingManager.lua"

config = 						"const/config.lua"
events = 						"const/events.lua"
files =							"const/files.lua"
filesNeeded =					"const/filesNeeded.lua"
items = 						"const/items.lua"
labels = 						"const/labels.lua"
protocols =						"const/protocols.lua"

brain =							"core/brain.lua"
multitasks =					"core/multitasks.lua"

register = 						"listeners/common/register.lua"
update = 						"listeners/common/update.lua"

getParkingPosition = 			"listeners/computer/getParkingPosition.lua"
getBatteryPosition = 			"listeners/computer/getBatteryPosition.lua"

batteryChargingSpaceDetected =	"listeners/server/batteryChargingSpaceDetected.lua"
emptyBatteryDetected =			"listeners/server/emptyBatteryDetected.lua"
initEntity =					"listeners/server/initEntity.lua"
registerEntity =				"listeners/server/registerEntity.lua"
registerPing =					"listeners/server/registerPing.lua"
taskFinished =					"listeners/server/taskFinished.lua"

chargeBattery =					"listeners/turtle/chargeBattery.lua"
free = 							"listeners/turtle/free.lua"
replaceBattery =				"listeners/turtle/replaceBattery.lua"

chat =							"managers/chat.lua"
checkBatteryChargingSpaces =	"managers/checkBatteryChargingSpaces.lua"
checkMissingEntities =			"managers/checkMissingEntities.lua"
monitorBattery =				"managers/monitorBattery.lua"
pingServer =					"managers/pingServer.lua"
tasks =							"managers/tasks.lua"

discord =						"misc/discord.lua"
entities =						"misc/entities.lua"
googleMaps =					"misc/googleMaps.lua"
interface = 					"misc/interface.lua"
inventory = 					"misc/inventory.lua"
scanner =						"misc/scanner.lua"
utils =							"misc/utils.lua"
